require: rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
