name: Ruby CI

on:
  push:
    branches: [ "staging", "production" ]
  pull_request:
    branches: [ "staging", "production" ]

jobs: 
  linters:
    runs-on: ubuntu-latest
    steps: 
      # Step: Check out the code.
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step: install ruby 
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with: 
          bundler-cache: true

      # Step: Install rubocop
      - name: Install rubocop
        run: |
          gem install rubocop
          gem install rubocop-rails

      # Step: Run linters
      - name: Run linters
        run: |
          rubocop --parallel
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run tests
        run: bin/rails test:all


          
      
