name: Ruby CI

on:
  push:
    branches: ["staging", "production"]
  pull_request:
    branches: ["staging", "production"]

jobs:
  linters:
    runs-on:
      - self-hosted
    steps:
      # Step: Check out the code.
      - name: Checkout code
        uses: actions/checkout@v3

      # Step: install ruby
      # - name: Setup Ruby and install gems
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     bundler-cache: true
      #     version: 3.2.0

      # Step: Install rubocop
      - name: Install rubocop
        run: |
          gem install rubocop
          gem install rubocop-rails

      # Step: Run linters
      - name: Run linters
        run: |
          rubocop --parallel
  test-1:
    name: Tests 1
    runs-on:
      - self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup Ruby and install gems
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     bundler-cache: true
      #     version: 3.2.0

      - name: Run tests
        run: bin/rails test:all
  test-2:
    name: Tests 2
    runs-on:
      - self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup Ruby and install gems
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     bundler-cache: true
      #     version: 3.2.0

      - name: Run tests
        run: bin/rails test:all
  test-3:
    name: Tests 3
    runs-on:
      - self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup Ruby and install gems
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     bundler-cache: true
      #     version: 3.2.0

      - name: Run tests
        run: bin/rails test:all
