name: Ruby CI

on:
  push:
    branches: ["staging", "production"]
  pull_request:
    branches: ["staging", "production"]

jobs:
  linters:
    runs-on:
      - self-hosted
    steps:
      # Step: Check out the code.
      - name: Checkout code
        uses: actions/checkout@v3

      # Step: install ruby
      - name: Install Ruby and dependencies
        run: |
          # Update and install necessary packages
          sudo apt-get update
          sudo apt-get install -y git curl

          # Install rbenv
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init -)"' >> ~/.bashrc
          source ~/.bashrc

          # Install ruby-build plugin
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc

          # Install Ruby
          rbenv install 3.2.0
          rbenv global 3.2.0
          ruby -v

          # Set up Ruby
          echo 'export PATH="$HOME/.rbenv/shims:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          rbenv rehash

          # Install Bundler
          gem install bundler

          # Install project dependencies
          bundle install

          # Run tests
          bundle exec rspec

      # Step: Install rubocop
      - name: Install rubocop
        run: |
          gem install rubocop
          gem install rubocop-rails

      # Step: Run linters
      - name: Run linters
        run: |
          rubocop --parallel
  test-1:
    name: Tests 1
    runs-on:
      - self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run tests
        run: bin/rails test:all
  test-2:
    name: Tests 2
    runs-on:
      - self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run tests
        run: bin/rails test:all
  test-3:
    name: Tests 3
    runs-on:
      - self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run tests
        run: bin/rails test:all
